# Code Generated by ZenTest v. 3.10.0
#                 classname: asrt / meth =  ratio%
#                   Wrapper:    0 /   12 =   0.00%

require 'test/unit' unless defined? $ZENTEST and $ZENTEST
require '..\lib\code_wrapper.rb'

class TestWrapper < Test::Unit::TestCase
  def test_process
    raise NotImplementedError, 'Need to write test_process'
  end
end

# Number of errors detected: 2
