# Code Generated by ZenTest v. 3.10.0
#                 classname: asrt / meth =  ratio%
#                  Platform:    0 /    1 =   0.00%

require 'test/unit' unless defined? $ZENTEST and $ZENTEST

class TestPlatform < Test::Unit::TestCase
  def test_check_operating_system
    raise NotImplementedError, 'Need to write test_check_operating_system'
  end
end

# Number of errors detected: 2
