Could not load lib\code_wrapper.rb: no such file to load -- ./platform
# Couldn't find class for name Wrapper
# Code Generated by ZenTest v. 3.10.0
#                 classname: asrt / meth =  ratio%
#                   Wrapper:    0 /   11 =   0.00%
# Number of errors detected: 0
